language: c
compiler:
  - clang
  - gcc
env:
  global:
    - PANIC_ACTION="gdb -batch -x raddb/panic.gdb %e %p 1>&0 2>&0"
    - secure: "H+uQeyOgsIyXtIPPG2VzAG8S/8KYGHlHaWhdiNuz1LM3SMcEKoPqG6o/P+HO8HVvYnA6nelyGuEryV90UfuwGY9YC6A/pqPQvx/gXSso63Zt66XSaiZjulCSm9OV8EB3wyWF7VSQ/ZHcn+L01hIlsQXTqLprMaC33cM0FYPr9fY="
  matrix:
    - LIBS_OPTIONAL=no LIBS_SHARED=yes
    - LIBS_OPTIONAL=yes LIBS_SHARED=yes
    - LIBS_OPTIONAL=yes LIBS_SHARED=yes BUILD_CFLAGS="-O2 -g3"
addons:
  coverity_scan:
    project:
      name: FreeRADIUS/freeradius-server
      version: v3.0.x
      description: The FreeRADIUS server project
    notification_email: freeradius-devel@lists.freeradius.org
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan
before_install:
  - $CC --version
  - wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - sudo sudo wget -O /etc/apt/sources.list.d/couchbase.list http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list
  - sudo apt-get update -qq
  - >
      sudo apt-get install --no-install-recommends -qq
      autoconf
      build-essential
      debhelper
      devscripts
      dh-make
      fakeroot
      gdb
      lintian
      pbuilder
      python-dev
      quilt
      libruby
      ruby-dev
      libcollectdclient-dev
      firebird-dev
      freetds-dev
      libcouchbase2-libevent
      libcouchbase-dev
      libcurl4-openssl-dev
      libgdbm-dev
      libhiredis-dev
      libidn11-dev
      libiodbc2-dev libiodbc2
      libjson0
      libjson0-dev
      libkrb5-dev
      libldap2-dev
      libpam0g-dev
      libpcap-dev
      libpcre3-dev
      libperl-dev
      libpq-dev
      libreadline-dev
      libsnmp-dev
      libssl-dev
      libtalloc-dev
      libtalloc2-dbg
      libunbound-dev
      libykclient-dev
      libyubikey-dev
  - sudo apt-get install -qq -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" libmysqlclient-dev
before_script:
  - CFLAGS="${BUILD_CFLAGS}" ./configure -C --enable-werror --prefix=$HOME/freeradius --with-shared-libs=$LIBS_SHARED --with-threads=$LIBS_OPTIONAL --with-udpfromto=$LIBS_OPTIONAL --with-openssl=$LIBS_OPTIONAL
  - make
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make travis-test; fi
