language: c
compiler:
- clang
- gcc
sudo: true
cache:
  apt: true
dist: xenial
env:
  global:
  - ASAN_OPTIONS="symbolize=1 detect_leaks=1 detect_stack_use_after_return=1"
  - LSAN_OPTIONS="fast_unwind_on_malloc=0:malloc_context_size=50"
  - KQUEUE_DEBUG="yes"
  - M_PERTURB=0x42
  - PANIC_ACTION="gdb -batch -x raddb/panic.gdb %e %p 1>&0 2>&0"
  - SQL_MYSQL_TEST_SERVER="127.0.0.1"
  - SQL_POSTGRESQL_TEST_SERVER="127.0.0.1"
  - LDAP_TEST_SERVER="127.0.0.1"
  - LDAP_TEST_SERVER_PORT="3890"
#  - REDIS_TEST_SERVER="127.0.0.1"
  - REDIS_IPPOOL_TEST_SERVER="127.0.0.1"
  - ANALYZE_C_DUMP="1"
  - FR_GLOBAL_POOL=2M
  - secure: H+uQeyOgsIyXtIPPG2VzAG8S/8KYGHlHaWhdiNuz1LM3SMcEKoPqG6o/P+HO8HVvYnA6nelyGuEryV90UfuwGY9YC6A/pqPQvx/gXSso63Zt66XSaiZjulCSm9OV8EB3wyWF7VSQ/ZHcn+L01hIlsQXTqLprMaC33cM0FYPr9fY=
  matrix:
  - TEST_CERTS=yes DO_BUILD=yes LIBS_OPTIONAL=no LIBS_SHARED=yes BUILD_CFLAGS="-DWITH_EVAL_DEBUG"
  - TEST_CERTS=yes DO_BUILD=yes LIBS_OPTIONAL=yes LIBS_SHARED=yes BUILD_CFLAGS="-DWITH_EVAL_DEBUG"
  - TEST_CERTS=yes DO_BUILD=yes LIBS_OPTIONAL=yes LIBS_SHARED=yes BUILD_CFLAGS="-DWITH_EVAL_DEBUG -O2 -g3"
  - TEST_CERTS=yes DO_BUILD=yes LIBS_OPTIONAL=yes LIBS_SHARED=yes BUILD_CFLAGS="-DNDEBUG"
  - DO_BUILD=no
notifications:
  slack:
    secure: DNYZ31leOmSYXFtHD/bERl4uwI1cZvDgBQQFsoH0/7/pXac2I293RhRS4TVo/ortlL1OCmilb4Hx8iwFLd+/7Pj9AHkxq6JlnVKKp2yhWLEwIYwYY5xPqO/lglzl5les6FIToSsU0dHusoYsNLYnRhQEnuIs+wy4tUp8eq/CvTs=
addons:
  coverity_scan:
    project:
      name: FreeRADIUS/freeradius-server
      version: v4.0.x
      description: The FreeRADIUS server project
    notification_email: freeradius-devel@lists.freeradius.org
    build_command_prepend: ./configure -with-rlm-python-bin=/usr/bin/python2.7
    build_command: make
    branch_pattern: coverity_scan
  postgresql: '10'
  apt:
    config:
      retries: true
    sources:
    - llvm-toolchain-xenial-7
    # For newer GCC
    - ubuntu-toolchain-r-test
    # For newer libkqueue
    - sourceline: ppa:rjvbertin/misc
    packages:
    - libjson-perl
    - autoconf
    - build-essential
    - clang-7
    - debhelper
    - devscripts
    - dh-make
    - doxygen
    - fakeroot
    - firebird-dev
    - freetds-dev
    - gcc-7
    - gccgo-7
    - gdb
    - graphviz
    - ldap-utils
    - libcollectdclient-dev
    - libcap-dev
    - libcurl4-openssl-dev
    - libgdbm-dev
    - libhiredis-dev
    - libidn11-dev
    - libiodbc2-dev
    - libiodbc2
    - libjson0
    - libjson0-dev
    - libkrb5-dev
    - libkqueue-dev
    - libldap2-dev
    - libluajit-5.1-dev
    - libmemcached-dev
    - libmysqlclient-dev
    - libnl-genl-3-dev
    - libpam0g-dev
    - libpcap-dev
    - libpcre3-dev
    - libperl-dev
    - libpq-dev
    - libpython-all-dev
    - libreadline-dev
    - libsnmp-dev
    - libssl-dev
    - libtalloc-dev
    - libtalloc2-dbg
    - libunbound-dev
    - libwbclient-dev
    - libykclient-dev
    - libyubikey-dev
    - lintian
    # Needed for llvm-symbolizer
    - llvm-7
    - luajit
    - lynx
    - mysql-server
    - pbuilder
    - postgresql-10
    - postgresql-client-10
    - python-dev
    - quilt
    # For rendering clang scan results
    - slapd
services:
- mysql
- postgresql
- redis-server
before_install:
- npm i -g @antora/cli@2.0 @antora/site-generator-default@2.0
- sudo ./scripts/travis/cassandra-install.sh
- rvm --install --default --binary use 2.4
- gem install asciidoctor
- wget -q -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb && sudo dpkg -i /tmp/pandoc.deb
- if [ "${CC}" == 'gcc' ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 && sudo update-alternatives --config gcc; fi
- if [ "${CC}" == 'clang' ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 60 && sudo update-alternatives --config clang; fi
- if [ "${CC}" == 'clang' ]; then sudo update-alternatives --install /usr/bin/llvm-symbolizer llvm-symbolizer /usr/bin/llvm-symbolizer-7 60 && sudo update-alternatives --config llvm-symbolizer; fi
- $CC --version
- make --version
- asciidoctor --version
- pandoc --version
- doxygen --version
before_script:
- ./scripts/travis/build.sh
script:
- if [ "${DO_BUILD}" = 'yes' -a "${COVERITY_SCAN_BRANCH}" != 1 ]; then make travis-test; fi
- if [ "${DO_BUILD}" = 'no' ]; then make tests.doc; fi
