language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtalloc-dev libssl-dev
  - sudo apt-get install -qq gdb
  - sudo apt-get install -qq build-essential autoconf dh-make debhelper devscripts fakeroot lintian pbuilder quilt
  - sudo apt-get install -qq -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" libmysqlclient-dev
  - sudo apt-get install -qq libkrb5-dev libgdbm-dev libhiredis-dev libldap2-dev libpam0g-dev libpcap-dev libperl-dev
  - sudo apt-get install -qq libpq-dev libreadline-dev libsnmp-dev libiodbc2-dev libyubikey-dev libykclient-dev firebird-dev
  - sudo apt-get install -qq  freetds-dev python-dev ruby-dev
env:
  - CFLAGS="-Wall $CFLAGS"
script:
  - ./configure -C --prefix=$HOME/travis
  - make -j8
  - make travis-test
