name: Documentation

on:
  push:
    branches-ignore: 
      - coverity_scan
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
        
    - name: Install common build dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
        asciidoctor \
        doxygen \
        graphviz
        
    - name: Install Antora
      run: |
        sudo npm i -g @antora/cli@2.0 @antora/site-generator-default@2.0;
        
    - name: Show versions
      run: |
        make --version
        doxygen --version
        asciidoctor --version

    - name: Build doxygen content
      run: |
         cd doc/doxygen;
         doxygen Doxyfile;
         
    - name: Deploy doxygen content to GitHub pages
      uses: appleboy/gh-pages-action@v0.0.2
      with:
        username: ${{ secrets.CI_DOCUMENTATION_DEPLOY_USER }}
        password: ${{ secrets.CI_DOCUMENTATION_DEPLOY_TOKEN }}
        remote_url: https://github.com/FreeRADIUS/freeradius.github.io.git
        target_branch: main
        pages_directory: doc/doxygen/html
        target_directory : doxygen
        
    - name: Build Antora docsite
      run: antora site.yml 
