name: Super-Linter

on:
  push:
    branches-ignore:
      - coverity_scan
  pull_request:

jobs:

  lint:
    name: Super-Linter. ${{ fromJSON('["Changes-only", "Full"]')[github.ref == 'refs/heads/linter' || github.ref == 'refs/heads/ci-debug'] }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#
#  shellcheck:
#    SC2223: This default assignment may cause DoS due to globbing. Quote it.
#      Easy to trigger and rarely a concern.
#
      - name: Configure the linters
        run: |
          echo 'disable=SC2223' > .shellcheckrc
          echo .shellcheckrc >> .gitignore

#
#  jscpd:
#    Disable entirely
#      Has a hair trigger and isn't useful enough to warrant tuning
#
#  sql-lint:
#    Disable entirely
#      Not suitable as a standalone linter
#
      - name: Lint
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (.*/)?(configure|config\.sub|config\.guess|missing|install-sh|freeradius\.css|toc_focus\.js|asciidoc/sass/.*\.scss)
          VALIDATE_ALL_CODEBASE: ${{ github.ref == 'refs/heads/linter' || github.ref == 'refs/heads/ci-debug' }}
          VALIDATE_JSCPD: false
          VALIDATE_SQL: false
